[package]
name = "solve_rust"
version = "0.1.0"
authors = ["Bjørn Tore Håvie <itsbth@itsbth.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
